### PR TITLE
Add some documentation for the project

### PR DESCRIPTION
**Pull request by mprahl**

### CODE REVIEW

**Comment by gnaponie** [comment]
For sure this is not the right place where to report that, but I've noticed while I was trying this PR.
I cloned the project and followed the doc for the installation. The server is running correctly, but I don't see any "input text" where I can "select an artifact". Am I missing something? Should I see that?
I attach a screenshot.
I'm using Firefox, but I have the same behavior also in Chromium. 
screenshot-2018-7-3 estuary

**Comment by yashvardhannanavati** [comment]
@gnaponie Just to confirm, were you also running estuary-api on your local machine? If not, then probably that is the reason you are not able to see the user input fields. By default, the front-end sends requests to the back-end on your localhost assuming it's running.

**Comment by yashvardhannanavati** [comment]
@gnaponie 
@mprahl and I just had a chat and we will add some more documentation to this PR regarding running estuary locally :)

**Comment by gnaponie** [comment]
@yashvardhannanavati yes, I was running it on my local machine (I've tried before a VM, I saw it was not working and I tried it on my local machine).

**Comment by mprahl** [comment]
@gnaponie thanks for your feedback! I added a way to start the local dev server using the production Estuary API with `ng serve --open -c local-prod-api` in the latest commit on this PR. That way you don't need to run the Estuary API yourself.

**Pull request merged**
